name: Create Namespace

on:
  workflow_dispatch:
      inputs:
        namespace:
          description: 'Kubernetes Namespace to be created'
          required: true
#   push:
#     branches:
#       - main

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: amjad-test    # Add your cluster name here.
  GKE_ZONE: us-east1-b   # Add your cluster zone here.
  DEPLOYMENT_NAME: nginx # Add your deployment name here.
  IMAGE: static-site

jobs:
  setup-build-publish-deploy:
    name: Create namespace
    runs-on: self-hosted-vm
    #runs-on: ubuntu-latest
    #environment: production
    

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v0.6.0
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}
        

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker
        

    # Get the GKE credentials so we can deploy to the cluster
    - uses: google-github-actions/get-gke-credentials@v0.8.0
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        credentials: ${{ secrets.GKE_SA_KEY }}
        
        
    - name: Setup kubectl
      id: install-kubectl
      uses: azure/setup-kubectl@v3

    # Create the name space
    - name: Create namespace
      run: |-
          kubectl create namespace ${{ inputs.namesapce }}
          kubectl get ns
